import { K8s, registerRoute, registerSidebarEntry } from '@kinvolk/headlamp-plugin/lib';
import { SectionBox, StatusLabel, Table } from '@kinvolk/headlamp-plugin/lib/components/common';
import { Alert, alpha, Box, Chip, FormControl, InputLabel, MenuItem, Select, Stack, Typography, useTheme } from '@mui/material';
import React from 'react';
import PenroseObserver from './penrose';

type Score=number|null;
type OsiSnapshot={observedAt:string;o:Score;s:Score;i:Score;confidenceO?:number;confidenceS?:number;confidenceI?:number};
type OsiRow=OsiSnapshot&{key:string;label:string;kind:string;state:string;diagnosis:string;history:OsiSnapshot[];measurements?:Record<string,any>;calculation?:Record<string,any>};
type FabricStatus={node:string;datapath?:{mode?:string;tunnelInterfaces?:string[]};frr?:{state?:string;bgp?:unknown};bgpRib?:any[];ecmpRoutes?:any[];pathRankings?:Record<string,unknown>;peerRoutes?:any[]};
type QualitySnapshot={sourceNode:string;sourcePlane:string;observedAt?:string;paths?:Array<{lossRatio?:number;p95Ms?:number}>;dns?:Array<{failureRatio?:number;p95Ms?:number}>};

const NetworkPathAssessment=K8s.crd.makeCustomResourceClass({apiInfo:[{group:'networking.re8ch.com',version:'v1alpha1'}],kind:'NetworkPathAssessment',pluralName:'networkpathassessments',singularName:'networkpathassessment',isNamespaced:false});
const raw=(item:any)=>item?.jsonData||item||{};
function parse(item:any,key:string){try{return JSON.parse(raw(item).data?.[key]);}catch{return null;}}
function bgpPeers(value:any):[number,number]{let up=0; let total=0;function visit(v:any){if(!v||typeof v!=='object')return;for(const[key,child]of Object.entries(v))if(key==='peers'&&child&&typeof child==='object')for(const peer of Object.values(child)as any[]){total++;if(String(peer?.state||peer?.peerState).toLowerCase()==='established')up++;}else visit(child);}visit(value);return[up,total];}
const axes={o:{x:54,y:8},s:{x:9,y:87},i:{x:99,y:87}}; const center={x:54,y:61};
function point(axis:keyof typeof axes,value:number){return{x:center.x+(axes[axis].x-center.x)*value,y:center.y+(axes[axis].y-center.y)*value};}
function timeColor(index:number,total:number){const t=total<=1?1:index/(total-1);return{stroke:`hsl(${215-35*t} 78% ${72-27*t}%)`,opacity:.12+.83*t,width:.8+1.8*t};}
const value=(score:Score)=>score===null||score===undefined?'—':score.toFixed(3);
function delta(history:OsiSnapshot[],axis:'o'|'s'|'i'){if(history.length<2)return'—';const a=history.at(-1)?.[axis]; const b=history.at(-2)?.[axis];if(a===null||a===undefined||b===null||b===undefined)return'—';const change=a-b;return`${change>=0?'+':''}${change.toFixed(3)}`;}

function OsiCard({row}:{row:OsiRow}){const theme=useTheme(); const history=row.history.slice(-18);const current=([['o',row.o],['s',row.s],['i',row.i]]as const).filter((entry):entry is[keyof typeof axes,number]=>entry[1]!==null&&entry[1]!==undefined).map(([axis,score])=>point(axis,score));const currentPath=current.length>1?[...current,...(current.length===3?[current[0]]:[])].map(p=>`${p.x},${p.y}`).join(' '):''; const traffic=row.measurements||{};
  return <Box sx={{border:`1px solid ${theme.palette.divider}`,borderRadius:3,p:{xs:2,md:3},background:alpha(theme.palette.primary.main,.025)}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={1}><Box><Typography variant="h5">{row.label}</Typography><Typography color="text.secondary">{row.kind} OSI assessment · {row.observedAt?new Date(row.observedAt).toLocaleString():'not observed'}</Typography></Box><Chip color={row.state==='Ready'?'success':row.state==='Partial'?'warning':'default'} label={row.state}/></Stack>
    <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'minmax(480px,1.35fr) minmax(320px,.65fr)'},gap:3,alignItems:'center'}}><svg viewBox="0 0 108 96" width="100%" style={{maxHeight:560,minHeight:360}} role="img" aria-label={`${row.label} O S I triangle`}><polygon points="54,8 9,87 99,87" fill="none" stroke={theme.palette.text.primary} strokeOpacity=".28" strokeWidth=".6"/>
      {[.25,.5,.75].map(level=><polygon key={level} points={(Object.keys(axes)as Array<keyof typeof axes>).map(axis=>{const p=point(axis,level);return`${p.x},${p.y}`;}).join(' ')} fill="none" stroke={theme.palette.text.primary} strokeOpacity=".09" strokeWidth=".25"/>)}{Object.values(axes).map((p,index)=><line key={index} x1={center.x} y1={center.y} x2={p.x} y2={p.y} stroke={theme.palette.text.primary} strokeOpacity=".14" strokeWidth=".3"/>)}
      {history.map((snapshot,index)=>{const color=timeColor(index,history.length); const points=([['o',snapshot.o],['s',snapshot.s],['i',snapshot.i]]as const).filter((entry):entry is[keyof typeof axes,number]=>entry[1]!==null&&entry[1]!==undefined).map(([axis,score])=>point(axis,score));if(points.length<2)return null;return <polyline key={`${snapshot.observedAt}-${index}`} points={[...points,...(points.length===3?[points[0]]:[])].map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={color.stroke} strokeOpacity={color.opacity*.48} strokeWidth={color.width*.45}/>;})}{currentPath&&<polyline points={currentPath} fill={alpha(theme.palette.primary.main,.16)} stroke={theme.palette.primary.main} strokeWidth="1.25" strokeLinejoin="round"/>}
      {(['o','s','i']as const).map(axis=>row[axis]===null?null:(()=>{const p=point(axis,row[axis]as number);return<circle key={axis} cx={p.x} cy={p.y} r="1.8" fill={theme.palette.primary.main}/>;})())}<text x="54" y="5" textAnchor="middle" fontSize="4.2" fontWeight="700" fill={theme.palette.text.primary}>O · Optimality {value(row.o)}</text><text x="2" y="94" fontSize="4.2" fontWeight="700" fill={theme.palette.text.primary}>S · Stability {value(row.s)}</text><text x="106" y="94" textAnchor="end" fontSize="4.2" fontWeight="700" fill={theme.palette.text.primary}>I · Independence {value(row.i)}</text></svg>
      <Stack gap={1.5}>{(['o','s','i']as const).map(axis=>{const confidenceKey=`confidence${axis.toUpperCase()}`as keyof OsiRow;return <Box key={axis} sx={{p:1.5,borderRadius:2,bgcolor:'background.paper'}}><Typography variant="overline">{axis.toUpperCase()} value</Typography><Typography variant="h4">{value(row[axis])}</Typography><Typography variant="caption" color="text.secondary">confidence {value(row[confidenceKey]as Score)} · Δ {delta(row.history,axis)}</Typography></Box>;})}{row.kind==='Service'&&<Stack direction="row" gap={1} flexWrap="wrap"><Chip label={`${Number(traffic.receivedBytes||0).toLocaleString()} bytes`}/><Chip label={`${Number(traffic.receivedPackets||0).toLocaleString()} packets`}/><Chip label={`${Number(traffic.requests||0).toLocaleString()} requests`}/><Chip label={`${traffic.windowSeconds||0}s window`}/><Chip label={`${traffic.sampleCount||0} samples`}/></Stack>}</Stack></Box>
    <Typography variant="subtitle2">Diagnosis</Typography><Typography sx={{mb:1.5}}>{row.diagnosis}</Typography>{row.calculation&&<Box component="pre" sx={{overflow:'auto',fontSize:12,maxHeight:260,p:1.5,bgcolor:'background.paper',borderRadius:2}}>{JSON.stringify(row.calculation,null,2)}</Box>}</Box>;}

function Dashboard(){const[maps,mapError]=K8s.ResourceClasses.ConfigMap.useList({namespace:'kube-system'}as any); const [assessments,npaError]=(NetworkPathAssessment as any).useList({refetchInterval:15000});
  const statuses=(maps||[]).filter((x:any)=>raw(x).metadata?.labels?.['networking.re8ch.com/node-status']==='true').map((x:any)=>parse(x,'status.json')).filter(Boolean).sort((a:FabricStatus,b:FabricStatus)=>a.node.localeCompare(b.node))as FabricStatus[];
  const quality=(maps||[]).filter((x:any)=>raw(x).metadata?.labels?.['app.kubernetes.io/component']==='network-quality').map((x:any)=>parse(x,'result.json')).filter(Boolean)as QualitySnapshot[];
  const clusterHistory=(maps||[]).filter((x:any)=>raw(x).metadata?.name==='advanced-fabric-osi-history').map((x:any)=>parse(x,'history.json')).find(Boolean)?.nodes as Record<string,OsiSnapshot[]>|undefined;
  const rows:OsiRow[]=(assessments||[]).map((item:any)=>{const resource=raw(item); const subject=resource.spec?.subjectRef||{}; const status=resource.status||{}; const dimensions=status.dimensions||{}; const confidence=status.confidence||{};const snapshot={observedAt:status.observedAt||'',o:dimensions.optimality??null,s:dimensions.stability??null,i:dimensions.independence??null,confidenceO:confidence.optimality,confidenceS:confidence.stability,confidenceI:confidence.independence};return{...snapshot,key:resource.metadata?.uid||resource.metadata?.name,label:subject.kind==='Service'?`${subject.namespace}/${subject.name}`:subject.name,kind:subject.kind||'Unknown',state:status.state||'Unknown',diagnosis:status.diagnosis||'No diagnosis.',measurements:status.measurements,calculation:status.calculation,history:subject.kind==='Node'?[...(clusterHistory?.[subject.name]||[])]:[snapshot]};}).sort((a:any,b:any)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label));
  const[selectedKey,setSelectedKey]=React.useState(''); const effectiveKey=rows.some(row=>row.key===selectedKey)?selectedKey:rows.find(row=>row.kind==='Service')?.key||rows[0]?.key||''; const selected=rows.find(row=>row.key===effectiveKey); const unknown=rows.filter(row=>[row.o,row.s,row.i].some(score=>score===null)).length;
  const qualityRows=quality.map(item=>{const paths=item.paths||[]; const dns=item.dns||[];return{source:`${item.sourceNode}/${item.sourcePlane}`,observed:item.observedAt?new Date(item.observedAt).toLocaleString():'unknown',pathSamples:paths.length,failedPaths:paths.filter(x=>Number(x.lossRatio||0)>0).length,pathP95:paths.length?Math.max(...paths.map(x=>Number(x.p95Ms||0))):0,dnsSamples:dns.length,failedDns:dns.filter(x=>Number(x.failureRatio||0)>0).length,dnsP95:dns.length?Math.max(...dns.map(x=>Number(x.p95Ms||0))):0};});
  const[selectedNode,setSelectedNode]=React.useState(''); const effectiveNode=statuses.some(x=>x.node===selectedNode)?selectedNode:statuses[0]?.node||''; const inspected=statuses.find(x=>x.node===effectiveNode); const ecmpRows=(inspected?.ecmpRoutes||[]).map((route:any)=>({destination:route.dst||'default',protocol:route.protocol||'—',metric:route.metric??'—',nextHops:(route.nexthops||[]).map((hop:any)=>`${hop.gateway||'on-link'} · ${hop.dev||'?'} · weight ${hop.weight||1}`)})); const decisionRows=Object.entries(inspected?.pathRankings||{}).flatMap(([profile,paths]:any)=>(paths||[]).map((path:any,index:number)=>({profile,rank:index+1,peer:path.peer,pathType:path.pathType||'—',score:path.score,quota:path.quotaPressure?.tier||'unknown',price:path.priceStatus||'unknown'}))); const peerRows=(inspected?.peerRoutes||[]).map((peer:any)=>({name:peer.name,role:peer.role||'—',class:peer.class||'—',internalIP:peer.internalIP||'—',acceleratedIP:peer.acceleratedIP||'—',podCIDR:peer.podCIDR||'—'})); const bgpRows=(inspected?.bgpRib||[]).flatMap((route:any)=>(route.paths||[]).map((path:any)=>({prefix:route.prefix,peer:path.peer||'—',nextHops:path.nextHops||[],asPath:path.asPath||'local',reason:path.best?'best':path.multipath?'multipath':'candidate only'})));
  return <Box sx={{p:2}}><Typography variant="h4">Advanced Fabric</Typography><Typography color="text.secondary">Measured Service inflow · explicit O/S/I values · one selected large triangle.</Typography>{(mapError||npaError)&&<Alert severity="error">Unable to read Advanced Fabric evidence: {String(mapError||npaError)}</Alert>}{unknown>0&&<Alert severity="info" sx={{my:2}}>{unknown} assessments retain unknown dimensions instead of rendering missing evidence as zero.</Alert>}
    <Stack direction={{xs:'column',md:'row'}} gap={2} sx={{my:2}} alignItems={{md:'center'}}><FormControl size="small" sx={{minWidth:{xs:'100%',md:420}}}><InputLabel id="osi-subject-label">OSI subject</InputLabel><Select labelId="osi-subject-label" label="OSI subject" value={effectiveKey} onChange={event=>setSelectedKey(event.target.value)}>{rows.map(row=><MenuItem key={row.key} value={row.key}>{row.kind} · {row.label}</MenuItem>)}</Select></FormControl><Chip label={`${rows.filter(row=>row.kind==='Service').length} measured services`}/><Chip label={`${rows.filter(row=>row.kind==='Node').length} nodes`}/></Stack>{selected?<OsiCard row={selected}/>:<Alert severity="warning">No NetworkPathAssessment has been published.</Alert>}
    <SectionBox title={`Raw measurement continuity (${quality.length} sources)`}><Table data={qualityRows} columns={[{header:'Source',accessorKey:'source'},{header:'Observed',accessorKey:'observed'},{header:'Path samples',accessorKey:'pathSamples'},{header:'Paths with loss',accessorKey:'failedPaths'},{header:'Worst path p95 ms',accessorKey:'pathP95'},{header:'DNS samples',accessorKey:'dnsSamples'},{header:'DNS failures',accessorKey:'failedDns'},{header:'Worst DNS p95 ms',accessorKey:'dnsP95'}]as any}/></SectionBox>
    <SectionBox title={`Node network status (${statuses.length})`}><Table data={statuses} columns={[{header:'Node',accessorKey:'node'},{header:'Datapath',accessorFn:(x:FabricStatus)=><Chip size="small" color={x.datapath?.mode==='native'?'success':'warning'} label={x.datapath?.mode||'unknown'}/>},{header:'Tunnel interface',accessorFn:(x:FabricStatus)=>x.datapath?.tunnelInterfaces?.join(', ')||'—'},{header:'FRR',accessorFn:(x:FabricStatus)=><StatusLabel status={x.frr?.state==='active'?'success':'error'}>{x.frr?.state||'unknown'}</StatusLabel>},{header:'BGP established',accessorFn:(x:FabricStatus)=>bgpPeers(x.frr?.bgp).join('/')},{header:'ECMP routes',accessorFn:(x:FabricStatus)=>x.ecmpRoutes?.length||0},{header:'Known peers',accessorFn:(x:FabricStatus)=>x.peerRoutes?.length||0}]as any}/></SectionBox>
    <Stack sx={{my:2}}><FormControl size="small" sx={{maxWidth:320}}><InputLabel id="af-node-label">Inspect node detail</InputLabel><Select labelId="af-node-label" label="Inspect node detail" value={effectiveNode} onChange={event=>setSelectedNode(event.target.value)}>{statuses.map(x=><MenuItem key={x.node} value={x.node}>{x.node}</MenuItem>)}</Select></FormControl></Stack>
    <SectionBox title={`${effectiveNode||'Node'}: kernel ECMP routes`}><Table data={ecmpRows} columns={[{header:'Destination',accessorKey:'destination'},{header:'Protocol',accessorKey:'protocol'},{header:'Metric',accessorKey:'metric'},{header:'Next hops / weight',accessorFn:(r:any)=>r.nextHops.join(', ')}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: path decisions`}><Table data={decisionRows} columns={[{header:'Profile',accessorKey:'profile'},{header:'Rank',accessorKey:'rank'},{header:'Peer',accessorKey:'peer'},{header:'Path type',accessorKey:'pathType'},{header:'Score',accessorKey:'score'},{header:'Quota',accessorKey:'quota'},{header:'Price',accessorKey:'price'}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: BGP candidate / selected paths`}><Table data={bgpRows} columns={[{header:'Prefix',accessorKey:'prefix'},{header:'Peer',accessorKey:'peer'},{header:'Next hops',accessorFn:(r:any)=>r.nextHops.join(', ')},{header:'AS path',accessorKey:'asPath'},{header:'Selection',accessorKey:'reason'}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: peer inventory`}><Table data={peerRows} columns={[{header:'Peer',accessorKey:'name'},{header:'Class',accessorKey:'class'},{header:'Role',accessorKey:'role'},{header:'Internal IP',accessorKey:'internalIP'},{header:'Accelerated IP',accessorKey:'acceleratedIP'},{header:'PodCIDR',accessorKey:'podCIDR'}]as any}/></SectionBox></Box>;}

registerSidebarEntry({name:'advanced-fabric',url:'/advanced-fabric',icon:'mdi:router-network',parent:'',label:'Advanced Fabric'});
registerRoute({path:'/advanced-fabric',sidebar:'advanced-fabric',name:'Advanced Fabric',component:()=><Dashboard/>});
registerSidebarEntry({name:'penrose-triangle',url:'/penrose-triangle',icon:'mdi:triangle-outline',parent:'',label:'Penrose Triangle'});
registerRoute({path:'/penrose-triangle',sidebar:'penrose-triangle',name:'Penrose Triangle Observer',component:()=><PenroseObserver/>});
