import { K8s, registerRoute, registerSidebarEntry } from '@kinvolk/headlamp-plugin/lib';
import { SectionBox, StatusLabel, Table } from '@kinvolk/headlamp-plugin/lib/components/common';
import { Alert, Box, Chip, FormControl, InputLabel, MenuItem, Select, Stack } from '@mui/material';
import React from 'react';
import PenroseObserver from './penrose';
import TradeoffObservatory from './tradeoff';

type FabricStatus={node:string;datapath?:{mode?:string;tunnelInterfaces?:string[]};frr?:{state?:string;bgp?:unknown};bgpRib?:any[];ecmpRoutes?:any[];pathRankings?:Record<string,unknown>;peerRoutes?:any[]};
type QualitySnapshot={sourceNode:string;sourcePlane:string;observedAt?:string;paths?:Array<{lossRatio?:number;p95Ms?:number}>;dns?:Array<{failureRatio?:number;p95Ms?:number}>};
type MeasurementRecord={symbol:string;state:'observed'|'partial'|'not-observed';observationStatus?:'measured'|'right-censored'|'incomplete'|'unavailable';value:any;source?:string;observedAt?:string;missingEvidence?:string;note?:string;censoring?:{kind?:string;windowStartedAt?:string;windowEndedAt?:string;eventObserved?:boolean}};
type NodeMeasurement={node:string;observedAt?:string;generatedAt?:string;envelopeComplete:boolean;coverage:{total:number;observed:number;partial:number;'not-observed':number};measurements:MeasurementRecord[]};

const SYMBOL_MEANINGS:Record<string,string>={
  x_nh:'selected next-hop identity',p_route:'route-selection preference attributes',w_ecmp:'installed ECMP width',m_route:'candidate-route multiplicity',n_path_change:'selected path-set transitions',d_mode:'Cilium forwarding mode',
  a_reach:'end-to-end reachability trials',l_path:'packet or connection loss ratio',t_rtt:'round-trip latency distribution',b_rx:'completed node-local Hubble/Gateway ingress window; available dimensions retain original units and zero is valid only after full window coverage',b_est:'established BGP sessions',n_peer:'configured and established peers',
  n_adv:'prefixes advertised to peers',n_recv:'prefixes received from peers',u_bgp:'BGP update events',w_bgp:'BGP withdrawal events',t_conv:'disturbance-to-stability time',lambda_flap:'route or peer flap intensity',
  delta_ribfib:'RIB/FIB state-set changes',n_nh:'candidate next-hop count',n_if:'distinct egress interfaces',n_tun:'distinct tunnel underlays',n_gw:'distinct gateways',n_asn:'observed upstream ASN dependency sets',
  g_dep:'shared routing/failure dependency graph',n_alt:'simultaneously viable alternatives',t_state:'state-transition timestamp',t_persist:'state persistence duration',f_switch:'path-switching frequency',t_recover:'impairment-to-recovery time',a_osc:'response oscillation amplitude',
};

const raw=(item:any)=>item?.jsonData||item||{};
function parse(item:any,key:string){try{return JSON.parse(raw(item).data?.[key]);}catch{return null;}}
function bgpPeers(value:any):[number,number]{let up=0; let total=0;function visit(v:any){if(!v||typeof v!=='object')return;for(const[key,child]of Object.entries(v))if(key==='peers'&&child&&typeof child==='object')for(const peer of Object.values(child)as any[]){total++;if(String(peer?.state||peer?.peerState).toLowerCase()==='established')up++;}else visit(child);}visit(value);return[up,total];}
function measurementValue(value:any){if(value===null||value===undefined)return'—';const encoded=typeof value==='string'?value:JSON.stringify(value);return encoded.length>180?`${encoded.slice(0,177)}…`:encoded;}

function Dashboard(){const[maps,mapError]=K8s.ResourceClasses.ConfigMap.useList({namespace:'kube-system'}as any);
  const statuses=(maps||[]).filter((x:any)=>raw(x).metadata?.labels?.['networking.re8ch.com/node-status']==='true').map((x:any)=>parse(x,'status.json')).filter(Boolean).sort((a:FabricStatus,b:FabricStatus)=>a.node.localeCompare(b.node))as FabricStatus[];
  const quality=(maps||[]).filter((x:any)=>raw(x).metadata?.labels?.['app.kubernetes.io/component']==='network-quality').map((x:any)=>parse(x,'result.json')).filter(Boolean)as QualitySnapshot[];
  const nodeMeasurements=(maps||[]).filter((x:any)=>raw(x).metadata?.labels?.['app.kubernetes.io/component']==='node-measurement').map((x:any)=>parse(x,'measurement.json')).filter(Boolean).sort((a:NodeMeasurement,b:NodeMeasurement)=>a.node.localeCompare(b.node))as NodeMeasurement[];
  const[selectedMeasurementNode,setSelectedMeasurementNode]=React.useState(''); const effectiveMeasurementNode=nodeMeasurements.some(x=>x.node===selectedMeasurementNode)?selectedMeasurementNode:nodeMeasurements[0]?.node||''; const selectedMeasurement=nodeMeasurements.find(x=>x.node===effectiveMeasurementNode); const censoredCount=(selectedMeasurement?.measurements||[]).filter(item=>item.observationStatus==='right-censored').length; const measurementRows=(selectedMeasurement?.measurements||[]).map(item=>({symbol:item.symbol,meaning:SYMBOL_MEANINGS[item.symbol]||'—',state:item.state,observation:item.observationStatus||item.state,value:item.observationStatus==='right-censored'?'— (right-censored)':measurementValue(item.value),source:item.source||'—',observed:item.observedAt?new Date(item.observedAt).toLocaleString():'—',evidence:item.missingEvidence||item.note||'—'}));
  const qualityRows=quality.map(item=>{const paths=item.paths||[]; const dns=item.dns||[];return{source:`${item.sourceNode}/${item.sourcePlane}`,observed:item.observedAt?new Date(item.observedAt).toLocaleString():'unknown',pathSamples:paths.length,failedPaths:paths.filter(x=>Number(x.lossRatio||0)>0).length,pathP95:paths.length?Math.max(...paths.map(x=>Number(x.p95Ms||0))):0,dnsSamples:dns.length,failedDns:dns.filter(x=>Number(x.failureRatio||0)>0).length,dnsP95:dns.length?Math.max(...dns.map(x=>Number(x.p95Ms||0))):0};});
  const[selectedNode,setSelectedNode]=React.useState(''); const effectiveNode=statuses.some(x=>x.node===selectedNode)?selectedNode:statuses[0]?.node||''; const inspected=statuses.find(x=>x.node===effectiveNode); const ecmpRows=(inspected?.ecmpRoutes||[]).map((route:any)=>({destination:route.dst||'default',protocol:route.protocol||'—',metric:route.metric??'—',nextHops:(route.nexthops||[]).map((hop:any)=>`${hop.gateway||'on-link'} · ${hop.dev||'?'} · weight ${hop.weight||1}`)})); const decisionRows=Object.entries(inspected?.pathRankings||{}).flatMap(([profile,paths]:any)=>(paths||[]).map((path:any,index:number)=>({profile,rank:index+1,peer:path.peer,pathType:path.pathType||'—',score:path.score,quota:path.quotaPressure?.tier||'unknown',price:path.priceStatus||'unknown'}))); const peerRows=(inspected?.peerRoutes||[]).map((peer:any)=>({name:peer.name,role:peer.role||'—',class:peer.class||'—',internalIP:peer.internalIP||'—',acceleratedIP:peer.acceleratedIP||'—',podCIDR:peer.podCIDR||'—'})); const bgpRows=(inspected?.bgpRib||[]).flatMap((route:any)=>(route.paths||[]).map((path:any)=>({prefix:route.prefix,peer:path.peer||'—',nextHops:path.nextHops||[],asPath:path.asPath||'local',reason:path.best?'best':path.multipath?'multipath':'candidate only'})));
  return <Box sx={{p:2}}>{mapError&&<Alert severity="error">Unable to read Advanced Fabric evidence: {String(mapError)}</Alert>}<TradeoffObservatory maps={maps||[]} measurements={nodeMeasurements}/>
    <Stack direction={{xs:'column',md:'row'}} gap={1.5} sx={{my:2}} alignItems={{md:'center'}}><FormControl size="small" sx={{minWidth:{xs:'100%',md:320}}}><InputLabel id="measurement-node-label">Measurement node</InputLabel><Select labelId="measurement-node-label" label="Measurement node" value={effectiveMeasurementNode} onChange={event=>setSelectedMeasurementNode(event.target.value)}>{nodeMeasurements.map(x=><MenuItem key={x.node} value={x.node}>{x.node}</MenuItem>)}</Select></FormControl>{selectedMeasurement&&<><Chip color={selectedMeasurement.envelopeComplete?'success':'error'} label={selectedMeasurement.envelopeComplete?'31-symbol envelope complete':'envelope incomplete'}/><Chip color="success" label={`${selectedMeasurement.coverage.observed} valid observations`}/>{censoredCount>0&&<Chip color="info" label={`${censoredCount} right-censored`}/>}<Chip color="warning" label={`${selectedMeasurement.coverage.partial} partial`}/><Chip label={`${selectedMeasurement.coverage['not-observed']} not observed`}/><Chip label={selectedMeasurement.generatedAt?new Date(selectedMeasurement.generatedAt).toLocaleString():'not generated'}/></>}</Stack>
    <SectionBox title={`Node measurement catalog (${nodeMeasurements.length} publishing nodes)`}>{selectedMeasurement?<Table data={measurementRows} columns={[{header:'Symbol',accessorKey:'symbol'},{header:'Meaning',accessorKey:'meaning'},{header:'Evidence state',accessorFn:(x:any)=><StatusLabel status={x.state==='observed'?'success':x.state==='partial'?'warning':'unknown'}>{x.state}</StatusLabel>},{header:'Observation result',accessorKey:'observation'},{header:'Value',accessorKey:'value'},{header:'Source',accessorKey:'source'},{header:'Observed',accessorKey:'observed'},{header:'Missing evidence / qualification',accessorKey:'evidence'}]as any}/>:<Alert severity="warning">No node measurement ConfigMap has been published.</Alert>}</SectionBox>
    <SectionBox title={`Raw measurement continuity (${quality.length} sources)`}><Table data={qualityRows} columns={[{header:'Source',accessorKey:'source'},{header:'Observed',accessorKey:'observed'},{header:'Path samples',accessorKey:'pathSamples'},{header:'Paths with loss',accessorKey:'failedPaths'},{header:'Worst path p95 ms',accessorKey:'pathP95'},{header:'DNS samples',accessorKey:'dnsSamples'},{header:'DNS failures',accessorKey:'failedDns'},{header:'Worst DNS p95 ms',accessorKey:'dnsP95'}]as any}/></SectionBox>
    <SectionBox title={`Node network status (${statuses.length})`}><Table data={statuses} columns={[{header:'Node',accessorKey:'node'},{header:'Datapath',accessorFn:(x:FabricStatus)=><Chip size="small" color={x.datapath?.mode==='native'?'success':'warning'} label={x.datapath?.mode||'unknown'}/>},{header:'Tunnel interface',accessorFn:(x:FabricStatus)=>x.datapath?.tunnelInterfaces?.join(', ')||'—'},{header:'FRR',accessorFn:(x:FabricStatus)=><StatusLabel status={x.frr?.state==='active'?'success':'error'}>{x.frr?.state||'unknown'}</StatusLabel>},{header:'BGP established',accessorFn:(x:FabricStatus)=>bgpPeers(x.frr?.bgp).join('/')},{header:'ECMP routes',accessorFn:(x:FabricStatus)=>x.ecmpRoutes?.length||0},{header:'Known peers',accessorFn:(x:FabricStatus)=>x.peerRoutes?.length||0}]as any}/></SectionBox>
    <Stack sx={{my:2}}><FormControl size="small" sx={{maxWidth:320}}><InputLabel id="af-node-label">Inspect node detail</InputLabel><Select labelId="af-node-label" label="Inspect node detail" value={effectiveNode} onChange={event=>setSelectedNode(event.target.value)}>{statuses.map(x=><MenuItem key={x.node} value={x.node}>{x.node}</MenuItem>)}</Select></FormControl></Stack>
    <SectionBox title={`${effectiveNode||'Node'}: kernel ECMP routes`}><Table data={ecmpRows} columns={[{header:'Destination',accessorKey:'destination'},{header:'Protocol',accessorKey:'protocol'},{header:'Metric',accessorKey:'metric'},{header:'Next hops / weight',accessorFn:(r:any)=>r.nextHops.join(', ')}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: path decisions`}><Table data={decisionRows} columns={[{header:'Profile',accessorKey:'profile'},{header:'Rank',accessorKey:'rank'},{header:'Peer',accessorKey:'peer'},{header:'Path type',accessorKey:'pathType'},{header:'Score',accessorKey:'score'},{header:'Quota',accessorKey:'quota'},{header:'Price',accessorKey:'price'}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: BGP candidate / selected paths`}><Table data={bgpRows} columns={[{header:'Prefix',accessorKey:'prefix'},{header:'Peer',accessorKey:'peer'},{header:'Next hops',accessorFn:(r:any)=>r.nextHops.join(', ')},{header:'AS path',accessorKey:'asPath'},{header:'Selection',accessorKey:'reason'}]as any}/></SectionBox><SectionBox title={`${effectiveNode||'Node'}: peer inventory`}><Table data={peerRows} columns={[{header:'Peer',accessorKey:'name'},{header:'Class',accessorKey:'class'},{header:'Role',accessorKey:'role'},{header:'Internal IP',accessorKey:'internalIP'},{header:'Accelerated IP',accessorKey:'acceleratedIP'},{header:'PodCIDR',accessorKey:'podCIDR'}]as any}/></SectionBox></Box>;}

registerSidebarEntry({name:'advanced-fabric',url:'/advanced-fabric',icon:'mdi:router-network',parent:'',label:'Advanced Fabric'});
registerRoute({path:'/advanced-fabric',sidebar:'advanced-fabric',name:'Advanced Fabric',component:()=><Dashboard/>});
registerSidebarEntry({name:'penrose-triangle',url:'/penrose-triangle',icon:'mdi:triangle-outline',parent:'',label:'Penrose Triangle'});
registerRoute({path:'/penrose-triangle',sidebar:'penrose-triangle',name:'Penrose Triangle Observer',component:()=><PenroseObserver/>});
