import { K8s } from '@kinvolk/headlamp-plugin/lib';
import { SectionBox, StatusLabel, Table } from '@kinvolk/headlamp-plugin/lib/components/common';
import { Alert, Box, Chip, FormControl, InputLabel, MenuItem, Select, Stack, Typography, useTheme } from '@mui/material';
import React from 'react';

const NetworkIntervention=K8s.crd.makeCustomResourceClass({apiInfo:[{group:'networking.re8ch.com',version:'v1alpha1'}],kind:'NetworkIntervention',pluralName:'networkinterventions',singularName:'networkintervention',isNamespaced:false});
const NetworkTradeoffEstimate=K8s.crd.makeCustomResourceClass({apiInfo:[{group:'networking.re8ch.com',version:'v1alpha1'}],kind:'NetworkTradeoffEstimate',pluralName:'networktradeoffestimates',singularName:'networktradeoffestimate',isNamespaced:false});
const TradeoffTriangle=K8s.crd.makeCustomResourceClass({apiInfo:[{group:'networking.re8ch.com',version:'v1alpha1'}],kind:'TradeoffTriangle',pluralName:'tradeofftriangles',singularName:'tradeofftriangle',isNamespaced:false});
const raw=(item:any)=>item?.jsonData||item||{};
function parse(item:any,key:string){try{return JSON.parse(raw(item).data?.[key]);}catch{return null;}}

const positions=[{x:54,y:8},{x:9,y:87},{x:99,y:87}];
function LargeTriangle({triangle,estimates,node}:{triangle:any;estimates:any[];node:string}){const theme=useTheme();const spec=triangle?.spec||{};const status=triangle?.status||{};const vertices=spec.vertices||['?','?','?'];const edges=spec.edges||[];const identified=edges.every((edge:string)=>estimates.some(item=>item.spec?.relation===edge&&item.status?.state==='Identified'&&item.spec?.subjectRef?.name===node));const closed=status.state==='Closed'&&identified;
  return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'minmax(520px,1.25fr) minmax(320px,.75fr)'},gap:3,alignItems:'center'}}><svg viewBox="0 0 108 96" width="100%" style={{maxHeight:590,minHeight:390}} role="img" aria-label={`${vertices.join(' ')} trade-off triangle ${closed?'closed':'open'}`}><polyline points="54,8 9,87" fill="none" stroke={theme.palette.text.primary} strokeOpacity=".3" strokeWidth=".8" strokeDasharray={closed?'':'2 2'}/><polyline points="9,87 99,87" fill="none" stroke={theme.palette.text.primary} strokeOpacity=".3" strokeWidth=".8" strokeDasharray={closed?'':'2 2'}/><polyline points="99,87 54,8" fill="none" stroke={theme.palette.text.primary} strokeOpacity=".3" strokeWidth=".8" strokeDasharray={closed?'':'2 2'}/>{closed&&<polygon points="54,20 20,79 88,79" fill={theme.palette.primary.main} fillOpacity=".15" stroke={theme.palette.primary.main} strokeWidth="1.2"/>}{vertices.map((vertex:string,index:number)=><g key={vertex}><circle cx={positions[index].x} cy={positions[index].y} r="2.2" fill={status.observedVertices?.includes(vertex)?theme.palette.success.main:theme.palette.grey[500]}/><text x={positions[index].x} y={index===0?4:94} textAnchor={index===1?'start':index===2?'end':'middle'} fontSize="5" fontWeight="700" fill={theme.palette.text.primary}>{vertex}</text></g>)}</svg><Stack gap={1.5}><Chip color={closed?'success':'warning'} label={closed?'Closed · observation-supported':'Open · Not identified'}/><Typography variant="h6">{spec.vertexLabel||vertices.join('–')}</Typography><Typography color="text.secondary">{spec.hypothesis||'No hypothesis description.'}</Typography>{edges.map((edge:string)=>{const estimate=estimates.find(item=>item.spec?.relation===edge&&item.spec?.subjectRef?.name===node);return <Box key={edge} sx={{p:1.5,borderRadius:2,bgcolor:'background.paper'}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{edge}</Typography><StatusLabel status={estimate?.status?.state==='Identified'?'success':estimate?.status?.state==='Confounded'?'error':'unknown'}>{estimate?.status?.state||'Not identified'}</StatusLabel></Stack><Typography variant="body2" color="text.secondary">τ {estimate?.status?.tau??'—'} · CI {estimate?.status?.confidenceInterval?JSON.stringify(estimate.status.confidenceInterval):'—'} · n {estimate?.status?.sampleCount??0}</Typography></Box>;})}</Stack></Box>;
}

export default function TradeoffObservatory({maps}:{maps:any[]}){const[triangles,triangleError]=(TradeoffTriangle as any).useList({refetchInterval:15000});const[estimates,estimateError]=(NetworkTradeoffEstimate as any).useList({refetchInterval:15000});const[interventions,interventionError]=(NetworkIntervention as any).useList({refetchInterval:15000});const structural=(maps||[]).map(item=>parse(item,'observations.json')).find(Boolean)?.nodes||{};const nodes=Object.keys(structural).sort();const[selectedNode,setSelectedNode]=React.useState('');const node=nodes.includes(selectedNode)?selectedNode:nodes[0]||'';const triangleItems=(triangles||[]).map(raw);const[selectedTriangle,setSelectedTriangle]=React.useState('');const triangleName=triangleItems.some((item:any)=>item.metadata?.name===selectedTriangle)?selectedTriangle:triangleItems[0]?.metadata?.name||'';const triangle=triangleItems.find((item:any)=>item.metadata?.name===triangleName);const estimateItems=(estimates||[]).map(raw);const interventionItems=(interventions||[]).map(raw).filter((item:any)=>!node||item.spec?.subjectRef?.name===node||item.spec?.subjectRef?.kind==='AdvancedFabric').sort((a:any,b:any)=>String(b.spec?.detectedAt).localeCompare(String(a.spec?.detectedAt)));const latent=structural[node]?.latent||{};const vertexRows=Object.entries(latent).map(([name,value]:any)=>({name,state:value.state,value:value.value??'Not identified',available:(value.availableSymbols||[]).join(', ')||'—',missing:(value.missingSymbols||[]).join(', ')||'—',reason:value.reason}));const interventionRows=interventionItems.map((item:any)=>({detected:item.spec?.detectedAt?new Date(item.spec.detectedAt).toLocaleString():'—',subject:`${item.spec?.subjectRef?.kind||'?'}/${item.spec?.subjectRef?.name||'?'}`,cause:item.spec?.cause,state:item.status?.identificationState||'Discovered',windows:JSON.stringify(item.spec?.windows||{}),confounders:(item.status?.confounders||[]).join(', ')||'—'}));
  return <Box><Typography variant="h4">Advanced Fabric · Trade-off Observatory</Typography><Typography color="text.secondary">Measurements → Q/K/H/C/R/D structures → interventions → finite differences. Correlation is not τ.</Typography>{(triangleError||estimateError||interventionError)&&<Alert severity="error" sx={{my:2}}>Unable to read Observatory APIs: {String(triangleError||estimateError||interventionError)}</Alert>}<Alert severity="info" sx={{my:2}}>Triangles remain open until all three structural observations and all three intervention-supported edges are identified. Missing evidence is never rendered as zero.</Alert><Stack direction={{xs:'column',md:'row'}} gap={2} sx={{my:2}}><FormControl size="small" sx={{minWidth:280}}><InputLabel id="tradeoff-subject">Research subject</InputLabel><Select labelId="tradeoff-subject" label="Research subject" value={node} onChange={event=>setSelectedNode(event.target.value)}>{nodes.map(value=><MenuItem key={value} value={value}>Node · {value}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:330}}><InputLabel id="tradeoff-triangle">Hypothesis / triangle</InputLabel><Select labelId="tradeoff-triangle" label="Hypothesis / triangle" value={triangleName} onChange={event=>setSelectedTriangle(event.target.value)}>{triangleItems.map((item:any)=><MenuItem key={item.metadata?.name} value={item.metadata?.name}>{item.spec?.vertexLabel||item.metadata?.name}</MenuItem>)}</Select></FormControl><Chip label="90 day research horizon"/><Chip label={`${interventionItems.length} interventions`}/></Stack>{triangle?<LargeTriangle triangle={triangle} estimates={estimateItems} node={node}/>:<Alert severity="warning">No TradeoffTriangle definitions have been published.</Alert>}<SectionBox title={`${node||'Subject'} structural quantities`}><Table data={vertexRows} columns={[{header:'Quantity',accessorKey:'name'},{header:'Evidence state',accessorFn:(x:any)=><StatusLabel status={x.state==='Observed'?'success':x.state==='Partial'?'warning':'unknown'}>{x.state}</StatusLabel>},{header:'Value',accessorKey:'value'},{header:'Available measurements',accessorKey:'available'},{header:'Missing measurements',accessorKey:'missing'},{header:'Identification',accessorKey:'reason'}]as any}/></SectionBox><SectionBox title="Intervention timeline / aligned-window readiness"><Table data={interventionRows} columns={[{header:'Detected',accessorKey:'detected'},{header:'Subject',accessorKey:'subject'},{header:'Cause',accessorKey:'cause'},{header:'Identification state',accessorFn:(x:any)=><StatusLabel status={x.state==='Eligible'?'success':x.state==='Confounded'?'error':'warning'}>{x.state}</StatusLabel>},{header:'Before / control / after',accessorKey:'windows'},{header:'Confounders',accessorKey:'confounders'}]as any}/></SectionBox></Box>;
}
